name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  native:
    strategy:
      fail-fast: false
      matrix:
        # Disabling the linux build for now
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: JUCE Linux Dependencies
        shell: bash
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y freeglut3-dev
          sudo apt-get install -y g++
          sudo apt-get install -y libasound2-dev
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y libfreetype6-dev
          sudo apt-get install -y libjack-jackd2-dev
          sudo apt-get install -y libx11-dev
          sudo apt-get install -y libxcomposite-dev
          sudo apt-get install -y libxcursor-dev
          sudo apt-get install -y libxinerama-dev
          sudo apt-get install -y libxrandr-dev
          sudo apt-get install -y mesa-common-dev

      - name: Build
        shell: bash
        run: |
          set -x
          set -e

          npm install
          npm run build

      - name: Artifact naming
        shell: bash
        run: |
          echo "ARTIFACT_DATESTRING=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "ARTIFACT_OS=$(echo $RUNNER_OS | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v3
        with:
          name: srvb-${{ env.ARTIFACT_OS }}-${{ env.ARTIFACT_DATESTRING }}
          path: |
            native/build/scripted/SRVB_artefacts/Release/VST3/
            native/build/scripted/SRVB_artefacts/Release/AU/
            !native/build/scripted/SRVB_artefacts/Release/VST3/*.lib
            !native/build/scripted/SRVB_artefacts/Release/VST3/*.exp
