name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  native:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build
        shell: bash
        run: |
          set -x
          set -e

          pushd js
          npm install
          npm run build
          popd

          # Build the native binaries
          mkdir -p ./build/native/
          pushd ./build/native/
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=./out/ \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
            ../..

          cmake --build . --config Release -j 8
          popd
