name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  native:
    strategy:
      fail-fast: false
      matrix:
        # Disabling the linux build for now
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: JUCE Linux Dependencies
        shell: bash
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y freeglut3-dev
          sudo apt-get install -y g++
          sudo apt-get install -y libasound2-dev
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y libfreetype6-dev
          sudo apt-get install -y libjack-jackd2-dev
          sudo apt-get install -y libx11-dev
          sudo apt-get install -y libxcomposite-dev
          sudo apt-get install -y libxcursor-dev
          sudo apt-get install -y libxinerama-dev
          sudo apt-get install -y libxrandr-dev
          sudo apt-get install -y mesa-common-dev

      - name: Build
        shell: bash
        run: |
          set -x
          set -e

          npm install
          npm run build
